# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranger-admin
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        image: zookage-util
        args:
        - wait-for-rollout
        - statefulset/postgres-database
      - name: create-ranger-database
        image: zookage-postgres
        command:
        - psql
        args:
        - 'postgresql://admin:admin@postgres-database-0.postgres-database:5432'
        - -c
        - 'CREATE DATABASE ranger'
      - name: setup-database
        image: zookage-ranger
        command:
        - python3
        args:
        - $(RANGER_HOME)/ranger-admin/db_setup.py
        envFrom:
        - configMapRef:
            name: ranger-env
        env:
        - name: RANGER_ADMIN_CONF
          value: $(RANGER_CONF)
        - name: RANGER_ADMIN_HOME
          value: $(RANGER_HOME)/ranger-admin
        volumeMounts:
        - name: ranger-conf
          mountPath: /etc/ranger/conf
      containers:
      - name: ranger-admin
        image: zookage-ranger
        command:
        - java
        args:
        - -Dservername=rangeradmin
        - -Dlogdir=/mnt/log
        - -Dcatalina.base=$(RANGER_HOME)/ranger-admin/ews
        - org.apache.ranger.server.tomcat.EmbeddedServer
        envFrom:
        - configMapRef:
            name: ranger-env
        env:
        - name: CLASSPATH
          # yamllint disable-line rule:line-length
          value: $(RANGER_CONF):$(RANGER_HADOOP_CONF_DIR):$(RANGER_HOME)/ranger-admin/ews/webapp/WEB-INF/classes/conf.dist:$(RANGER_HOME)/lib/*:$(RANGER_HOME)/ranger-admin/ews/lib/*:$(RANGER_HOME)/ranger-admin/ews/webapp/WEB-INF/lib/*:$(RANGER_HOME)/ranger-admin/ews/ranger_jaas/*
        readinessProbe:
          tcpSocket:
            port: 6080
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: hive-conf
          mountPath: /etc/hive/conf
        - name: ranger-conf
          mountPath: /etc/ranger/conf
        - name: mnt
          mountPath: /mnt
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: hive-conf
        configMap:
          name: hive-conf
      - name: ranger-conf
        configMap:
          name: ranger-conf
      - name: mnt
        emptyDir: {}
