# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    component: secret
secretGenerator:
- literals:
  - AWS_ACCESS_KEY_ID=zookage
  - AWS_SECRET_ACCESS_KEY=dummy
  name: aws-secret
- literals:
  - TRINO_REST_CATALOG_OAUTH2_CLIENT_ID=trino
  - TRINO_REST_CATALOG_OAUTH2_CLIENT_SECRET=trino
  name: trino-secret
- files:
  - hadoop/hadoop.jceks
  name: hadoop-secret
- files:
  - hdfs/hdfs-http-auth-signature.secret
  - hdfs/httpfs-signature.secret
  name: hdfs-secret
- files:
  - hive/beeline.jceks
  name: hive-secret
- files:
  - hive-metastore/hive-metastore.jceks
  name: hive-metastore-secret
- files:
  - ozone/ozone-http-auth-signature.secret
  name: ozone-secret
- files:
  - yarn/yarn-http-auth-signature.secret
  name: yarn-secret
