# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-metastore
spec:
  selector:
    matchLabels: {}
  serviceName: hive-metastore
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        image: zookage-util
        args:
        - wait-for-rollout
        - statefulset/hive-postgres
      - name: init-schema
        image: zookage-hive
        command:
        - $(HIVE_HOME)/bin/schematool
        args:
        - -initSchema
        - -dbType
        - postgres
        envFrom:
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: hive-env
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: hive-conf
          mountPath: /etc/hive/conf
        - name: package-hadoop
          mountPath: /opt/hadoop
      containers:
      - name: metastore
        image: zookage-hive
        command:
        - $(HIVE_HOME)/bin/schematool
        args:
        - --service
        - metastore
        envFrom:
        - configMapRef:
            name: aws-env
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: hive-env
        readinessProbe:
          tcpSocket:
            port: 9083
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: hive-conf
          mountPath: /etc/hive/conf
        - name: package-hadoop
          mountPath: /opt/hadoop
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: hive-conf
        configMap:
          name: hive-conf
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
  volumeClaimTemplates: []
