apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-metastore
spec:
  selector:
    matchLabels: {}
  serviceName: hive-metastore
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        image: zookage-util
        args:
        - wait-for-rollout
        - statefulset/hive-postgres
      - name: init-schema
        image: zookage-hive
        command:
        - $(HIVE_HOME)/bin/schematool
        args:
        - -initSchema
        - -dbType
        - postgres
        envFrom:
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: hive-env
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: hive-conf
          mountPath: /etc/hive/conf
        - name: package-hadoop
          mountPath: /opt/hadoop
      containers:
      - name: metastore
        image: zookage-hive
        command:
        - $(HIVE_HOME)/bin/schematool
        args:
        - --service
        - metastore
        envFrom:
        - configMapRef:
            name: aws-env
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: hive-env
        readinessProbe:
          tcpSocket:
            port: 9083
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: hive-conf
          mountPath: /etc/hive/conf
        - name: package-hadoop
          mountPath: /opt/hadoop
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: hive-conf
        configMap:
          name: hive-conf
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
  volumeClaimTemplates: []
