# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapreduce-historyserver
spec:
  selector:
    matchLabels: {}
  serviceName: mapreduce-historyserver
  replicas: 1
  template:
    spec:
      initContainers:
      - name: wait-for-history-dir
        image: zookage-util
        args:
        - wait-for-job
        - mapreduce-mkdir
      containers:
      - name: historyserver
        image: zookage-hadoop
        command:
        - $(HADOOP_HOME)/bin/mapred
        args:
        - historyserver
        envFrom:
        - configMapRef:
            name: hadoop-env
        readinessProbe:
          tcpSocket:
            port: 10020
        securityContext:
          runAsUser: 1013
          runAsGroup: 1010
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: mnt
          mountPath: /mnt
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
  volumeClaimTemplates: []
