apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-metastore
spec:
  selector:
    matchLabels: {}
  serviceName: hive-metastore
  replicas: 1
  template:
    spec:
      initContainers:
      - name: cleanup
        image: zookage-hive
        command:
        - rm
        args:
        - -rf
        - /mnt/hive/metastore
        volumeMounts:
        - name: mnt
          mountPath: /mnt
      - name: init-schema
        image: zookage-hive
        command:
        - $(HIVE_HOME)/bin/schematool
        args:
        - -initSchema
        - -dbType
        - derby
        envFrom:
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: hive-metastore-env
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: hive-metastore-conf
          mountPath: /etc/hive/conf
        - name: mnt
          mountPath: /mnt
        - name: package-hadoop
          mountPath: /opt/hadoop
      - name: wait-for-warehouse-dir
        image: zookage-util
        args:
        - wait-for-job
        - hive-mkdir
      containers:
      - name: metastore
        image: zookage-hive
        command:
        - $(HIVE_HOME)/bin/hive
        args:
        - --service
        - metastore
        envFrom:
        - configMapRef:
            name: aws-env
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: hive-metastore-env
        readinessProbe:
          tcpSocket:
            port: 9083
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: hive-metastore-conf
          mountPath: /etc/hive/conf
        - name: mnt
          mountPath: /mnt
        - name: package-hadoop
          mountPath: /opt/hadoop
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: hive-metastore-conf
        configMap:
          name: hive-metastore-conf
      - name: mnt
        emptyDir: {}
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
  volumeClaimTemplates: []
