# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-directory-server
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    spec:
      initContainers:
      - name: setup-conf
        image: zookage-directory-server
        command:
        - bash
        args:
        - -c
        - |
          mkdir /mnt/default/conf
          cp /etc/directory-server/conf/log4j.properties /mnt/default/conf
        volumeMounts:
        - name: directory-server-conf
          mountPath: /etc/directory-server/conf
        - name: mnt
          mountPath: /mnt/default
      containers:
      - name: server
        image: zookage-directory-server
        command:
        - /bin/bash
        args:
        - /opt/directory-server/bin/apacheds.sh
        - run
        env:
        - name: ADS_INSTANCES
          value: /mnt
        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              ldapmodify -x \
                -H "ldap://localhost:10389" \
                -D uid=admin,ou=system \
                -w secret \
                -f /etc/directory-server/conf/enable-nis-schema.ldif
              ldapadd -x -c \
                -H "ldap://localhost:10389" \
                -D uid=admin,ou=system \
                -w secret \
                -f /etc/directory-server/conf/bootstrap.ldif
        readinessProbe:
          tcpSocket:
            port: 10389
        volumeMounts:
        - name: directory-server-conf
          mountPath: /etc/directory-server/conf
        - name: mnt
          mountPath: /mnt/default
      terminationGracePeriodSeconds: 5
      volumes:
      - name: directory-server-conf
        configMap:
          name: directory-server-conf
      - name: mnt
        emptyDir: {}
