# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: tez-deploy
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-kdc
        image: zookage-util
        args:
        - wait-for-rollout
        - deployment/kerberos-kdc
      - name: kinit
        image: zookage-util
        command:
        - /usr/bin/kinit
        args:
        - -c
        - /var/kerberos/krb5cc
        - -kt
        - /etc/tez/secrets/tez.keytab
        - tez@ZOOKAGE.LOCAL
        volumeMounts:
        - name: kerberos-conf
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
        - name: tez-secret
          mountPath: /etc/tez/secrets
        - name: kerberos-cache
          mountPath: /var/kerberos
      containers:
      - name: upload
        env:
        - name: HADOOP_SECURITY_AUTHENTICATION
          value: kerberos
        - name: HADOOP_RPC_PROTECTION
          value: authentication
        - name: KRB5CCNAME
          value: FILE:/var/kerberos/krb5cc
        volumeMounts:
        - name: kerberos-conf
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
        - name: kerberos-cache
          mountPath: /var/kerberos
      volumes:
      - name: kerberos-conf
        configMap:
          name: kerberos-conf
      - name: tez-secret
        secret:
          secretName: tez-secret
      - name: kerberos-cache
        emptyDir: {}
