commonLabels:
  component: config
configMapGenerator:
- name: hadoop-conf
  files:
  - hadoop/capacity-scheduler.xml
  - hadoop/core-site.xml
  - hadoop/hadoop-metrics2.properties
  - hadoop/hdfs-site.xml
  - hadoop/httpfs-log4j.properties
  - hadoop/httpfs-signature.secret
  - hadoop/httpfs-site.xml
  - hadoop/log4j.properties
  - hadoop/mapred-site.xml
  - hadoop/yarn-site.xml
- name: hbase-conf
  files:
  - hbase/hadoop-metrics2-hbase.properties
  - hbase/hbase-site.xml
  - hbase/log4j.properties
- name: hive-conf
  files:
  - hive/beeline-hs2-connection.xml
  - hive/hive-log4j2.properties
  - hive/hive-site.xml
- name: ozone-conf
  files:
  - ozone/dn-audit-log4j2.properties
  - ozone/hadoop-metrics2-hddsdatanode.properties
  - ozone/hadoop-metrics2-ozonemanager.properties
  - ozone/hadoop-metrics2-recon.properties
  - ozone/hadoop-metrics2-s3gateway.properties
  - ozone/hadoop-metrics2-storagecontainermanager.properties
  - ozone/hadoop-metrics2-xceiverclientmetrics.properties
  - ozone/http_secret
  - ozone/log4j.properties
  - ozone/om-audit-log4j2.properties
  - ozone/ozone-site.xml
  - ozone/s3g-audit-log4j2.properties
  - ozone/scm-audit-log4j2.properties
- name: spark-conf
  files:
  - spark/log4j.properties
  - spark/spark-defaults.conf
  - spark/spark-env.sh
- name: tez-conf
  files:
  - tez/tez-site.xml
- name: trino-catalog
  files:
  - trino/catalog/hive.properties
  - trino/catalog/tpcds.properties
- name: trino-conf
  files:
  - trino/cli.properties
  - trino/config-coordinator.properties
  - trino/config-worker.properties
  - trino/jvm.config
  - trino/log.properties
  - trino/node.properties
- name: zookeeper-conf
  files:
  - zookeeper/log4j.properties
  - zookeeper/zoo.cfg
