# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    component: config
configMapGenerator:
- files:
  - hadoop/capacity-scheduler.xml
  - hadoop/core-site.xml
  - hadoop/hadoop-metrics2.properties
  - hadoop/hdfs-site.xml
  - hadoop/httpfs-log4j.properties
  - hadoop/httpfs-signature.secret
  - hadoop/httpfs-site.xml
  - hadoop/log4j.properties
  - hadoop/mapred-site.xml
  - hadoop/yarn-site.xml
  - hadoop/ranger-hdfs-audit.xml
  - hadoop/ranger-hdfs-policymgr-ssl.xml
  - hadoop/ranger-hdfs-security.xml
  - hadoop/ranger-yarn-audit.xml
  - hadoop/ranger-yarn-policymgr-ssl.xml
  - hadoop/ranger-yarn-security.xml
  name: hadoop-conf
- files:
  - hbase/hadoop-metrics2-hbase.properties
  - hbase/hbase-site.xml
  - hbase/log4j2.properties
  - hbase/ranger-hbase-audit.xml
  - hbase/ranger-hbase-policymgr-ssl.xml
  - hbase/ranger-hbase-security.xml
  name: hbase-conf
- files:
  - hive/beeline-hs2-connection.xml
  - hive/hive-log4j2.properties
  - hive/hive-site.xml
  - hive/ranger-hive-audit.xml
  - hive/ranger-hive-policymgr-ssl.xml
  - hive/ranger-hive-security.xml
  name: hive-conf
- files:
  - hive-metastore/metastore-log4j2.properties
  - hive-metastore/metastore-site.xml
  - hive-metastore/ranger-hive-audit.xml
  - hive-metastore/ranger-hive-policymgr-ssl.xml
  - hive-metastore/ranger-hive-security.xml
  name: hive-metastore-conf
- files:
  - keycloak/keycloak.conf
  - keycloak/realm-export.json
  name: keycloak-conf
- files:
  - openldap/bootstrap.ldif
  name: openldap-conf
- files:
  - ozone/dn-audit-log4j2.properties
  - ozone/hadoop-metrics2-hddsdatanode.properties
  - ozone/hadoop-metrics2-ozonemanager.properties
  - ozone/hadoop-metrics2-recon.properties
  - ozone/hadoop-metrics2-s3gateway.properties
  - ozone/hadoop-metrics2-storagecontainermanager.properties
  - ozone/hadoop-metrics2-xceiverclientmetrics.properties
  - ozone/http_secret
  - ozone/log4j.properties
  - ozone/om-audit-log4j2.properties
  - ozone/ozone-site.xml
  - ozone/s3g-audit-log4j2.properties
  - ozone/scm-audit-log4j2.properties
  - ozone/ranger-ozone-audit.xml
  - ozone/ranger-ozone-policymgr-ssl.xml
  - ozone/ranger-ozone-security.xml
  name: ozone-conf
- files:
  - ranger/install.properties
  - ranger/logback.xml
  - ranger/ranger-admin-site.xml
  - ranger/ranger-ugsync-site.xml
  - ranger/ranger-role-hbase-admin.json
  - ranger/ranger-role-hdfs-admin.json
  - ranger/ranger-role-hive-admin.json
  - ranger/ranger-role-mapred-admin.json
  - ranger/ranger-role-ozone-admin.json
  - ranger/ranger-role-ranger-admin.json
  - ranger/ranger-role-spark-admin.json
  - ranger/ranger-role-tez-admin.json
  - ranger/ranger-role-trino-admin.json
  - ranger/ranger-role-warehouse-admin.json
  - ranger/ranger-role-yarn-admin.json
  - ranger/ranger-service-hbase.json
  - ranger/ranger-service-hdfs.json
  - ranger/ranger-service-hive.json
  - ranger/ranger-service-ozone.json
  - ranger/ranger-service-trino.json
  - ranger/ranger-service-yarn.json
  - ranger/ranger-policies.json
  name: ranger-conf
- files:
  - spark/log4j.properties
  - spark/spark-defaults.conf
  - spark/spark-env.sh
  name: spark-conf
- files:
  - tez/tez-site.xml
  name: tez-conf
- files:
  - trino/catalog/hive.properties
  - trino/catalog/iceberg.properties
  - trino/catalog/tpcds.properties
  - trino/catalog/tpch.properties
  name: trino-catalog
- files:
  - trino/cli.properties
  - trino/config-coordinator.properties
  - trino/config-worker.properties
  - trino/jvm.config
  - trino/log.properties
  - trino/node.properties
  - trino/access-control-default.properties
  - trino/access-control-ranger.properties
  - trino/ranger-trino-audit.xml
  - trino/ranger-trino-policymgr-ssl.xml
  - trino/ranger-trino-security.xml
  name: trino-conf
- files:
  - zookeeper/log4j.properties
  - zookeeper/zoo.cfg
  name: zookeeper-conf
